
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 11 16:39:33 BRT 2018
//----------------------------------------------------

package generator;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RPARENT = 35;
  public static final int LPARENT = 34;
  public static final int LESSTHEN = 62;
  public static final int FUNCTION = 11;
  public static final int LBRACKET = 36;
  public static final int GREATERTHENEQUALS = 65;
  public static final int CONST = 4;
  public static final int WITH = 25;
  public static final int PACKED = 12;
  public static final int EQUALS = 60;
  public static final int STRINGCHARACTERCLOSURE = 59;
  public static final int DIVEXTENSION = 28;
  public static final int CASE = 24;
  public static final int REPEAT = 19;
  public static final int ARRAY = 13;
  public static final int FORWARD = 7;
  public static final int MINUS = 38;
  public static final int SEMICOLON = 44;
  public static final int NOT = 27;
  public static final int AND = 30;
  public static final int RECORD = 31;
  public static final int TYPE = 5;
  public static final int NIL = 26;
  public static final int IN = 66;
  public static final int OR = 29;
  public static final int COMMA = 45;
  public static final int DOUBLEDOT = 47;
  public static final int DIV = 40;
  public static final int BEGIN = 8;
  public static final int UNTIL = 20;
  public static final int SCALEFACTOR = 67;
  public static final int DIGIT = 53;
  public static final int PLUS = 39;
  public static final int SINGLEQUOTE = 48;
  public static final int DOT = 46;
  public static final int OF = 14;
  public static final int EOF = 0;
  public static final int RBRACKET = 37;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int NUMBER = 55;
  public static final int MOD = 42;
  public static final int CIRCUNFLEX = 51;
  public static final int LESSTHENEQUALS = 63;
  public static final int TIMES = 41;
  public static final int COLON = 43;
  public static final int GREATERTHEN = 64;
  public static final int EXTERNAL = 15;
  public static final int LETTER = 56;
  public static final int DOUBLEQUOTE = 49;
  public static final int TO = 21;
  public static final int FILE = 33;
  public static final int GOTO = 16;
  public static final int WHILE = 17;
  public static final int THEN = 23;
  public static final int END = 9;
  public static final int STRING = 57;
  public static final int DIGITSEQUENCE = 54;
  public static final int DIFF = 61;
  public static final int DOWNTO = 22;
  public static final int STRINGCHARACTER = 58;
  public static final int ASSIGMENT = 50;
  public static final int LABEL = 3;
  public static final int VAR = 6;
  public static final int PROCEDURE = 10;
  public static final int DO = 18;
  public static final int SET = 32;
  public static final int IDENTIFIER = 52;
}

