
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 05 00:54:59 BRT 2018
//----------------------------------------------------

package generator;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LPARENT = 32;
  public static final int RPARENT = 33;
  public static final int LESSTHEN = 60;
  public static final int LBRACKET = 34;
  public static final int GREATERTHENEQUALS = 63;
  public static final int CONST = 4;
  public static final int WITH = 21;
  public static final int PACKED = 10;
  public static final int EQUALS = 58;
  public static final int STRINGCHARACTERCLOSURE = 57;
  public static final int DIVEXTENSION = 24;
  public static final int CASE = 20;
  public static final int REPEAT = 15;
  public static final int FORWARD = 7;
  public static final int MINUS = 36;
  public static final int SEMICOLON = 42;
  public static final int NOT = 23;
  public static final int AND = 26;
  public static final int RECORD = 29;
  public static final int TYPE = 5;
  public static final int NIL = 22;
  public static final int IN = 64;
  public static final int OR = 25;
  public static final int COMMA = 43;
  public static final int DOUBLEDOT = 45;
  public static final int DIV = 38;
  public static final int BEGIN = 8;
  public static final int UNTIL = 16;
  public static final int SCALEFACTOR = 65;
  public static final int DIGIT = 51;
  public static final int PLUS = 37;
  public static final int SINGLEQUOTE = 46;
  public static final int DOT = 44;
  public static final int OF = 11;
  public static final int EOF = 0;
  public static final int RBRACKET = 35;
  public static final int TRUE = 27;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int NUMBER = 53;
  public static final int MOD = 40;
  public static final int CIRCUNFLEX = 49;
  public static final int LESSTHENEQUALS = 61;
  public static final int TIMES = 39;
  public static final int COLON = 41;
  public static final int GREATERTHEN = 62;
  public static final int EXTERNAL = 12;
  public static final int LETTER = 54;
  public static final int DOUBLEQUOTE = 47;
  public static final int TO = 17;
  public static final int FILE = 31;
  public static final int WHILE = 13;
  public static final int THEN = 19;
  public static final int END = 9;
  public static final int STRING = 55;
  public static final int DIGITSEQUENCE = 52;
  public static final int DIFF = 59;
  public static final int DOWNTO = 18;
  public static final int STRINGCHARACTER = 56;
  public static final int ASSIGMENT = 48;
  public static final int FALSE = 28;
  public static final int LABEL = 3;
  public static final int VAR = 6;
  public static final int DO = 14;
  public static final int SET = 30;
  public static final int IDENTIFIER = 50;
}

