
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 05 23:03:06 BRT 2018
//----------------------------------------------------

package generator;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LPARENT = 29;
  public static final int RPARENT = 30;
  public static final int LESSTHEN = 57;
  public static final int LBRACKET = 31;
  public static final int GREATERTHENEQUALS = 60;
  public static final int CONST = 4;
  public static final int WITH = 18;
  public static final int PACKED = 10;
  public static final int EQUALS = 55;
  public static final int STRINGCHARACTERCLOSURE = 54;
  public static final int DIVEXTENSION = 21;
  public static final int CASE = 17;
  public static final int FORWARD = 7;
  public static final int MINUS = 33;
  public static final int SEMICOLON = 39;
  public static final int NOT = 20;
  public static final int AND = 23;
  public static final int RECORD = 26;
  public static final int TYPE = 5;
  public static final int NIL = 19;
  public static final int IN = 61;
  public static final int OR = 22;
  public static final int COMMA = 40;
  public static final int DOUBLEDOT = 42;
  public static final int DIV = 35;
  public static final int BEGIN = 8;
  public static final int SCALEFACTOR = 62;
  public static final int DIGIT = 48;
  public static final int PLUS = 34;
  public static final int SINGLEQUOTE = 43;
  public static final int DOT = 41;
  public static final int OF = 11;
  public static final int EOF = 0;
  public static final int RBRACKET = 32;
  public static final int TRUE = 24;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int NUMBER = 50;
  public static final int MOD = 37;
  public static final int CIRCUNFLEX = 46;
  public static final int LESSTHENEQUALS = 58;
  public static final int TIMES = 36;
  public static final int COLON = 38;
  public static final int GREATERTHEN = 59;
  public static final int EXTERNAL = 12;
  public static final int LETTER = 51;
  public static final int DOUBLEQUOTE = 44;
  public static final int TO = 15;
  public static final int FILE = 28;
  public static final int WHILE = 13;
  public static final int THEN = 16;
  public static final int END = 9;
  public static final int STRING = 52;
  public static final int DIGITSEQUENCE = 49;
  public static final int DIFF = 56;
  public static final int STRINGCHARACTER = 53;
  public static final int ASSIGMENT = 45;
  public static final int FALSE = 25;
  public static final int LABEL = 3;
  public static final int VAR = 6;
  public static final int DO = 14;
  public static final int SET = 27;
  public static final int IDENTIFIER = 47;
}

